repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-ast
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-json
    - id: check-added-large-files
    - id: debug-statements


-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black

-   repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
    - id: isort

# -   repo: https://github.com/twu/skjold
#     rev: v0.6.2
#     hooks:
#     - id: skjold
#       verbose: true  # Important if used with `report_only`, see below.
